name: Deploy workflow

on:
  push:
    branches: 
      -  main
    paths-ignore: 
      -  '**/*.md'
      -  '**/.gitignore'
      -  '**/LICENSE'
  pull_request:
    branches:
      -  main
  workflow_dispatch:

concurrency: 
  group: Deploy
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'
          cache: 'npm'
          
      - name: Installing dependencies
        run: npm install --ignore-scripts
        
      - name: Running scripts
        env: 
          TIMEOUT: ${{vars.URL_CHECKER_TIMEOUT}}
        run: |
          shopt -s globstar nullglob
          for script in script/**/*.js; do
            node "$script" --timeout "$TIMEOUT" 
          done
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pages
        uses: actions/configure-pages@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'
          cache: 'npm'
          
      - name: Installing dependencies
        run: npm install --ignore-scripts

      - name: Build static pages
        env: 
          PATH_PREFIX: /${{ github.event.repository.name }}/
        run: npm run prod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
         
        
          
