name: Deploy workflow

on:
  push:
    branches: 
      -  main
    paths-ignore: 
      -  '**/*.md'
      -  '**/.gitignore'
      -  '**/LICENSE'
  pull_request:
    branches:
      -  main
  workflow_dispatch:

concurrency: 
  group: Deploy
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          
      - name: Installing dependencies
        run: npm ci
        
      - name: Running scripts
        run: |
          for script in scripts/**/*.js
            node "$script"
          done


          
